"""empty message

Revision ID: 581b8b9db6f8
Revises: 638e6feb3132
Create Date: 2021-08-01 23:52:57.603846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581b8b9db6f8'
down_revision = '638e6feb3132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pubDate', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('director', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(), nullable=False),
    sa.Column('lead_actor1', sa.String(), nullable=True),
    sa.Column('lead_actor2', sa.String(), nullable=True),
    sa.Column('sub_actor1', sa.String(), nullable=True),
    sa.Column('sub_actor2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_title'], ['movies.title'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    op.drop_table('movies')
    # ### end Alembic commands ###
