"""empty message

Revision ID: 638e6feb3132
Revises: c21fd506a25d
Create Date: 2021-08-01 23:37:43.311874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638e6feb3132'
down_revision = 'c21fd506a25d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('lead_actor1', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('lead_actor2', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('sub_actor1', sa.String(), nullable=True))
    op.add_column('actors', sa.Column('sub_actor2', sa.String(), nullable=True))
    op.drop_column('actors', 'name')
    op.add_column('movies', sa.Column('publisher', sa.String(), nullable=True))
    op.drop_column('movies', 'filmMake')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('filmMake', sa.VARCHAR(), nullable=True))
    op.drop_column('movies', 'publisher')
    op.add_column('actors', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('actors', 'sub_actor2')
    op.drop_column('actors', 'sub_actor1')
    op.drop_column('actors', 'lead_actor2')
    op.drop_column('actors', 'lead_actor1')
    # ### end Alembic commands ###
